---

- name: create web instances
  ec2:
    region: us-east-1
    image: ami-2d39803a
    instance_type: t2.nano
    count: 1
    vpc_subnet_id: "{{ item['vpc_subnet_id'] }}"
    assign_public_ip: no
    termination_protection: no
    monitoring: no
    private_ip: "{{ item['private_ip'] }}"
    user_data: "{{ lookup('file', 'roles/aws/files/web_user_data_file') }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 32
        delete_on_termination: true
      - device_name: /dev/sdb
        volume_size: 8
        delete_on_termination: true
    instance_tags:
      Name: "{{ item['Name'] }}"
    group: default
    key_name: producao-infra
    state: present
    wait: true
  with_items: "{{ web_hosts }}"

- name: add new instances to web_group
  add_host: name={{ item['Name'] }} ansible_ssh_user={{ ansible_ssh_user }} ansible_ssh_host={{ item['private_ip'] }} ansible_ssh_private_key_file={{ ansible_ssh_private_key_file }} group=web_group
  with_items: "{{ web_hosts }}"

- name: wait for instance's ssh to come up
  wait_for: host={{ item['private_ip'] }} port=22 delay=60 timeout=320 state=started
  with_items: '{{ web_hosts }}'
