---
# tasks file for common

- name: update apt cache
  apt: update_cache=yes

- name: set system timezone
  copy: content='America/Sao_Paulo' dest=/etc/timezone owner=root group=root mode=0644
  notify: update timezone

- name: generate pt_BR.UTF-8 locales
  locale_gen: name=pt_BR.UTF-8 state=present
  notify: update locales

- name: upgrade all system packages
  apt: upgrade=dist

- name: install packages
  apt: name={{ item }} state=present autoremove=yes
  with_items:
    - ntp

- name: turns vim default system editor
  alternatives: name=editor path=/usr/bin/vim.basic

- name: change .bashrc file for user root
  copy: src=.bashrc.root dest=/root/.bashrc owner=root group=root mode=0644

- name: change .bashrc file for user ubuntu
  copy: src=.bashrc.ubuntu dest=/home/ubuntu/.bashrc owner=ubuntu group=ubuntu mode=0644
